# configuration for building multihead model
body: 'unet++'

channels:
  # base channels for model
  base_ch: 32

clamp:
  # clamping range
  range: [1e-4, 1e4]

conditioning:
  # mode of conditioning: 'none', 'concat', 'film', 'hybrid'
  mode: 'hybrid'
  # concat pathway
  concat_out_dim: 4
  concat_use_ids: True
  concat_use_vec: True
  concat_use_mlp: True
  # FiLM pathway
  film_embed_dim: 4
  film_use_ids: True
  film_use_vec: True
  film_hidden: 128
