# training data
training:
  images:
    - name: work
      path: ./data/work/data/training/image.tif
  labels:
    - name: work
      path: ./data/work/data/training/label.tif
# inference data
inference:
  images:
    - name: work
      path: ./data/work/data/inference/image.tif
# domain data
domain:
  training:
    disc:
      - name: ecodist
        path: ./data/work/data/training/ecodistrict.tif
      - name: geology
        path: ./data/work/data/training/geology.tif
    cont: null
  inference:
    disc:
      - name: ecodist
        path: ./data/work/data/inference/ecodistrict.tif
      - name: geology
        path: ./data/work/data/inference/geology.tif
    cont: null
# shared data configuration
config: ./data/work/config.json