# Config for training phases

name: control

# experiment config (consumed by controller)
experiment:
  ckpt_dpath: ./checkpoints
  preview_dpath: ./previews

phases:
  # each phase
  phase_1:
    name: Phase 1
    num_epochs: 100
    active_heads: [layer1]
    masked_classes:
      layer1: [4, 6]
    frozen_heads: null
    lr_scale: 1.0

  # phase_2:
  #   name: Phase 2
  #   num_epochs: 5
  #   active_heads: [layer1, layer2_2]
  #   frozen_heads: null
  #   lr_scale: 1.0

  # phase_3:
  #   name: Phase 3
  #   num_epochs: 5
  #   active_heads: [layer1, layer2_2, layer2_5]
  #   frozen_heads: null
  #   lr_scale: 1.0