# training data
training:
  image: ./demo_data/training/image.tif
  label: ./demo_data/training/label.tif
# inference data
inference:
  image: ./demo_data/inference/image.tif
# data configuration
config: ./demo_data/config.json