# location to store grid and domain artifacts (static & versioned)
artifacts:
  root: ./artifacts
  grids: ${paths.artifacts.root}/world_grids
  domain: ${paths.artifacts.root}/domain_knowledge

# location to store data cache and related files
cache:
  root: ./data_cache
  training:
    root: ${paths.data.cache}/training
    blocks: ${paths.data.cache.root}/blocks
  inference:
    root: ${paths.data.cache}/inference
    blocks: ${paths.data.cache.root}/blocks
