# main project configuration

# default subconfigs
defaults:
  - _self_
  - cache: cache
  - dataset: demo
  - models: multihead
  - trainer: runtime
  - curriculum: control
  - grid: base
  - grid/extent_mode: ref

# dataset name
dataset_name: ${hydra:runtime.choices.dataset}

# data preparation mode
# can be skip, with_inference, no_inference, or inference_only
dataprep_mode: with_inference

# training mode
# can be with_inference or no_inference
trainer_mode: with_inference