# -----------------------------default  subconfigs-----------------------------
defaults:
  - _self_
  - artifacts: default
  - dataproc: default
  - curriculum: demo
  - extent: demo
  - dataset: demo
  - domain: demo
  - grid: base
  - models: multihead
  - trainer: default

# ----------------------------------------------------------------------------
# dataset name
dataset_name: ${hydra:runtime.choices.dataset}

# data preparation mode
# can be skip, with_inference, no_inference, or inference_only
dataprep_mode: skip

# training mode
# can be with_inference or no_inference
trainer_mode: with_inference