# conf/main.yaml

# the defaults list
defaults:
  - dataset/input: input.yaml
  - dataset/cache: cache.yaml
  - models: multihead
  - trainer/config: config.yaml
  - curriculum: control
  - _self_

# top-level and overrides
seed: 42
test:
  # if not zero randomly select n training blocks and n/5 validation blocks
  rand_sample_n: 0
# can be skip, training, inference, training+inference
dataprep:
  dataset_name: demo
  mode: train_only
