# conf/main.yaml

# the defaults list
defaults:
  - dataset/input: input.yaml
  - dataset/cache: cache.yaml
  - models: multihead
  - trainer: config/config.yaml
  - curriculum: control
  - grid: grid/base.yaml
  - _self_

# top-level and overrides
seed: 42
test:
  # if not zero randomly select n training blocks and n/5 validation blocks
  rand_sample_n: 0

# can be skip, with_inference, no_inference, or inference_only
dataprep:
  dataset_name: work
  mode: with_inference

# can be with_inference or no_inference
trainer_mode: with_inference