# cache directory structure
root: ./artifacts
grids: ${artifacts.root}/world_grids
domain: ${artifacts.root}/domain_knowledge
cache: ${artifacts.root}/data_cache

# get current dataset in use
dataset_name: ${hydra:runtime.choices.dataset}

# derived paths for current dataset
# from fit input data
fit: ${artifacts.root}/${dataset_name}/fit
fit_blocks_dir: ${artifacts.fit}/blocks
fit_all_blocks: ${artifacts.fit}/all_blocks.json
fit_valid_blocks: ${artifacts.fit}/valid_blocks.json
#
fit_image_stats: ${artifacts.fit}/image_stats.json
label_count_global: ${artifacts.fit}/count_global.json
label_count_train: ${artifacts.fit}/count_train.json
block_scores: ${artifacts.fit}/score.json
train_blocks_split: ${artifacts.fit}/train_blocks_split.json
val_blocks_split: ${artifacts.fit}/val_blocks_split.json
# from user-provided test data
test: ${artifacts.root}/${dataset_name}/test
test_blocks_dir: ${artifacts.test}/blocks
test_all_blocks: ${artifacts.test}/all_blocks.json
#
test_image_stats: ${artifacts.test}/image_stats.json