# cache directory structure
root: ./artifacts
grids: ${artifacts.root}/world_grids
domain: ${artifacts.root}/domain_knowledge
cache: ${artifacts.root}/data_cache

# derived paths for current dataset (dirname = dataset name)
# fit input data
fit: ${artifacts.cache}/${dataset.name}/fit
# fit blocks building
fit_raster_windows: ${artifacts.fit}/fit_raster_windows.pkl
fit_blocks_dir: ${artifacts.fit}/blocks
fit_all_blocks: ${artifacts.fit}/all_blocks.json
fit_valid_blocks: ${artifacts.fit}/valid_blocks.json
# fit blocks stats for normalization
fit_image_stats: ${artifacts.fit}/image_stats.json
# train/val split reltead
label_count_global: ${artifacts.fit}/count_global.json
block_scores: ${artifacts.fit}/score.json
train_blocks_split: ${artifacts.fit}/train_blocks_split.json
val_blocks_split: ${artifacts.fit}/val_blocks_split.json
# train data label count for downstream, e.g., LA
label_count_train: ${artifacts.fit}/count_train.json
# test input data (optional)
test: ${artifacts.cache}/${dataset.name}/test
# test blocks building
test_raster_windows: ${artifacts.test}/test_raster_windows.pkl
test_blocks_dir: ${artifacts.test}/blocks
test_all_blocks: ${artifacts.test}/all_blocks.json
# test blocks stats for normalization
test_image_stats: ${artifacts.test}/image_stats.json